name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup Geode SDK
      uses: geode-sdk/cli@main
      
    - name: Build mod
      run: geode build
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wraith-helper-windows
        path: build/*.geode
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.geode
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
